/**
 * generated by: https://jvilk.com/MakeTypes/
 */
export type { GetTrackPageInfoResult } from './getTrackPageInfo';
export type { GetCurrentUserResult } from './getCurrentUser';
export type { GetPlayHistoryResult } from './getPlayHistory';
export type { GetSubscriptionsResult } from './getSubscriptions';
export type { GetFavoritesResult } from './getFavorites';
export type { GetPurchasedAlbumsResult } from './getPurchasedAlbums';
export type { GetAlbumWithTracksResult } from './getAlbumWithTracks';
export type { GetUserPubResult } from './getUserPub';
export type { GetUserInfoResult } from './getUserInfo';
export type { GetTracksOfAlbumResult } from './getTracksOfAlbum';
export type { GetCommentsOfTracksResult } from './getCommentsOfTrack';
export type { GetTrackAudioResult } from './getTrackAudio';
export type { GetNonFreeTrackAudioResult } from './getNonFreeTrackAudio';
export type { GetContextTracksResult } from './getContextTracks';
export type { GetRecommendResult } from './getRecomends';
export type { GetCategoriesResult } from './getCategories';

export * from './utils';
